### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Trickiy** [Asu-chan/RiivolutionIsoBuilder#1]
QUESTION: i probably am just being a idiot but how how do i input the commands like changing the tittle id? i did read the optionspart of the readme i simply don't know how to use it.

**Comment by ghost** [comment]
RiivolutionIsoBuilder.exe --title-id [title id]

And if you want to use multiple Options at once:
RiivolutionIsoBuilder.exe --title-id [title id] --game-name [name of the game]

**Comment by ghost** [comment]
I forgot to say this but you need to type these commands into a cmd window

**Comment by Trickiy** [comment]
so I execute the exe then title id ide i want like this? RiivolutionIsoBuilder.exe --title-id 6789fg then add a space and type th --game name marios final adventure  right?

**Comment by Trickiy** [comment]
sorry i have yet to understand commands still new to using windows.

**Comment by ghost** [comment]
> so I execute the exe then title id ide i want like this? RiivolutionIsoBuilder.exe --title-id 6789fg then add a space and type th --game name marios final adventure  right?

Open a Command Prompt window in where the RiivolutionIsoBuilder.exe is located and then type this command: RiivolutionIsoBuilder.exe --title-id 6789fg --game-name Marios Final Adventure

**Comment by Trickiy** [comment]
Ok Thanks

**Comment by Asu-chan** [comment]
Closing this since it seems to have been resolved.
